// Mock данные пока бэкенд ещё не готов
// Переключить USE_MOCK = true в api.js

export const mockUsers = [
    {
        id: 1,
        email: 'admin@mtscloud.ru',
        name: 'Администратор',
        role: 'admin',
        password: 'admin123',
    },
    {
        id: 2,
        email: 'client@company.ru',
        name: 'ООО Компания',
        role: 'client',
        tenantId: 't-1',
        password: 'client123',
    },
    {
        id: 3,
        email: 'demo@startup.ru',
        name: 'Стартап Технологии',
        role: 'client',
        tenantId: 't-2',
        password: 'demo123',
    },
];

export const mockTenants = [
    {
        id: 't-1',
        name: 'ООО Компания',
        email: 'client@company.ru',
        status: 'active',
        createdAt: '2024-11-15T10:00:00Z',
        quota: {
            maxVMs: 10,
            maxCPU: 32,
            maxRAM: 64,
            maxDisk: 1000,
        },
        usage: {
            vms: 3,
            cpu: 8,
            ram: 16,
            disk: 250,
        },
    },
    {
        id: 't-2',
        name: 'Стартап Технологии',
        email: 'demo@startup.ru',
        status: 'active',
        createdAt: '2025-01-10T14:30:00Z',
        quota: {
            maxVMs: 5,
            maxCPU: 16,
            maxRAM: 32,
            maxDisk: 500,
        },
        usage: {
            vms: 2,
            cpu: 4,
            ram: 8,
            disk: 100,
        },
    },
    {
        id: 't-3',
        name: 'Банк Финанс',
        email: 'it@bankfinans.ru',
        status: 'active',
        createdAt: '2024-08-20T09:00:00Z',
        quota: {
            maxVMs: 20,
            maxCPU: 64,
            maxRAM: 128,
            maxDisk: 2000,
        },
        usage: {
            vms: 8,
            cpu: 24,
            ram: 48,
            disk: 800,
        },
    },
    {
        id: 't-4',
        name: 'ИП Иванов',
        email: 'ivanov@mail.ru',
        status: 'suspended',
        createdAt: '2025-03-01T12:00:00Z',
        quota: {
            maxVMs: 3,
            maxCPU: 8,
            maxRAM: 16,
            maxDisk: 200,
        },
        usage: {
            vms: 1,
            cpu: 2,
            ram: 4,
            disk: 50,
        },
    },
];

export const mockVMs = [
    {
        id: 'vm-101',
        tenantId: 't-1',
        name: 'web-server-01',
        status: 'running',
        os: 'Ubuntu 22.04',
        cpu: 2,
        ram: 4,
        disk: 80,
        ip: '10.10.1.10',
        network: 'vnet-t1',
        createdAt: '2025-01-20T08:00:00Z',
    },
    {
        id: 'vm-102',
        tenantId: 't-1',
        name: 'db-server-01',
        status: 'running',
        os: 'Ubuntu 22.04',
        cpu: 4,
        ram: 8,
        disk: 120,
        ip: '10.10.1.11',
        network: 'vnet-t1',
        createdAt: '2025-01-21T10:00:00Z',
    },
    {
        id: 'vm-103',
        tenantId: 't-1',
        name: 'dev-env',
        status: 'stopped',
        os: 'Debian 12',
        cpu: 2,
        ram: 4,
        disk: 50,
        ip: '10.10.1.12',
        network: 'vnet-t1',
        createdAt: '2025-02-01T12:00:00Z',
    },
    {
        id: 'vm-201',
        tenantId: 't-2',
        name: 'app-backend',
        status: 'running',
        os: 'CentOS 9',
        cpu: 2,
        ram: 4,
        disk: 60,
        ip: '10.20.1.10',
        network: 'vnet-t2',
        createdAt: '2025-02-15T09:30:00Z',
    },
    {
        id: 'vm-202',
        tenantId: 't-2',
        name: 'test-env',
        status: 'stopped',
        os: 'Ubuntu 22.04',
        cpu: 2,
        ram: 4,
        disk: 40,
        ip: '10.20.1.11',
        network: 'vnet-t2',
        createdAt: '2025-03-01T14:00:00Z',
    },
    {
        id: 'vm-301',
        tenantId: 't-3',
        name: 'core-banking-01',
        status: 'running',
        os: 'RHEL 9',
        cpu: 4,
        ram: 8,
        disk: 200,
        ip: '10.30.1.10',
        network: 'vnet-t3',
        createdAt: '2024-09-10T07:00:00Z',
    },
    {
        id: 'vm-302',
        tenantId: 't-3',
        name: 'core-banking-02',
        status: 'running',
        os: 'RHEL 9',
        cpu: 4,
        ram: 8,
        disk: 200,
        ip: '10.30.1.11',
        network: 'vnet-t3',
        createdAt: '2024-09-10T07:00:00Z',
    },
];

export const mockNetworks = [
    {
        id: 'vnet-t1',
        tenantId: 't-1',
        name: 'Default Network',
        subnet: '10.10.1.0/24',
        gateway: '10.10.1.1',
        vlan: 101,
        isolated: true,
    },
    {
        id: 'vnet-t2',
        tenantId: 't-2',
        name: 'Default Network',
        subnet: '10.20.1.0/24',
        gateway: '10.20.1.1',
        vlan: 102,
        isolated: true,
    },
    {
        id: 'vnet-t3',
        tenantId: 't-3',
        name: 'Default Network',
        subnet: '10.30.1.0/24',
        gateway: '10.30.1.1',
        vlan: 103,
        isolated: true,
    },
];

export const mockDashboardStats = {
    totalTenants: 4,
    activeTenants: 3,
    totalVMs: 7,
    runningVMs: 5,
    totalCPU: { used: 38, total: 128 },
    totalRAM: { used: 76, total: 256 },
    totalDisk: { used: 1200, total: 4000 },
    resourceHistory: [
        { time: '00:00', cpu: 25, ram: 30, disk: 28 },
        { time: '04:00', cpu: 22, ram: 29, disk: 28 },
        { time: '08:00', cpu: 35, ram: 35, disk: 29 },
        { time: '12:00', cpu: 45, ram: 40, disk: 30 },
        { time: '16:00', cpu: 42, ram: 38, disk: 30 },
        { time: '20:00', cpu: 30, ram: 32, disk: 30 },
        { time: 'Сейчас', cpu: 29, ram: 30, disk: 30 },
    ],
};